port = 5003
install = "pip install -r physio1/requirements.txt"
start = "python physio1/app.py"
healthcheck_path = "/"
env = ["PHYSIO_ADMIN_USER", "PHYSIO_ADMIN_PASS", "PHYSIO_SECRET_KEY"]
env_optional = ["PHYSIO_STRIPE_SECRET_KEY", "PHYSIO_STRIPE_PUBLIC_KEY", "PHYSIO_PRODUCTION"]
